#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Config-Grammar
Version  : 1.12
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/D/DS/DSCHWEI/Config-Grammar-1.12.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/D/DS/DSCHWEI/Config-Grammar-1.12.tar.gz
Summary  : 'A grammar-based, user-friendly config parser'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-Config-Grammar-man

%description
Config::Grammar
===============
Config::Grammar is a Perl module to parse configuration files by
following a grammar, which specifies how the configuration file should
look like. The configuration files are nice to work with for humans
and the error messages are helpful because it tells right away that
for example you are setting a variable which isn't defined.

%package man
Summary: man components for the perl-Config-Grammar package.
Group: Default

%description man
man components for the perl-Config-Grammar package.


%prep
%setup -q -n Config-Grammar-1.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Config/Grammar.pm
/usr/lib/perl5/site_perl/5.26.1/Config/Grammar/Document.pm
/usr/lib/perl5/site_perl/5.26.1/Config/Grammar/Dynamic.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Config::Grammar.3
/usr/share/man/man3/Config::Grammar::Dynamic.3
